# xt_config_schema.yaml: yaml file that describes legal entries for DEFAULT and LOCAL XT config files.

# predefined keys: $record-types, $repeat, $opt, $select, $select-key, $select-records
# predefined values: $str, $bool, $int, $num, $str-list, $rec

$record-types:
    rec_philly: {type: "philly"}
    rec_batch: {type: "batch", key: $str, url: $str }
    rec_aml: {type: "aml", subscription-id: $str, resource-group: $str}
    rec_storage: {type: "storage", provider: $str, $opt: {key: $str, path: $str, name: $str}}
    rec_mongo: {type: "mongo", mongo-connection-string: $str}
    rec_vault: {type: "vault", url: $str}
    rec_registry: {type: "registry", login-server: $str, $opt: {username: $str, password: $str, login: $bool}}

    rec_service: {service: $str, $opt: 
        {vm-size: $str, azure-image: $str, low-pri: $bool, box-class: $str, docker: $str, setup: $str, 
        boxes: $str-list, vc: $str, cluster: $str, queue: $str, sku: $str, compute: $str, nodes: $int, name: $str }}

    rec_docker: {registry: $str, image: $str}
    rec_setup: { $opt: {activate: $str, conda-packages: $str-list, pip-packages: $str-list } }
    rec_image: {offer: $str, publisher: $str, sku: $str, node-agent-sku-id: $str, version: $str}
    rec_box: {address: $str, max-runs: $int, $opt: {os: $str, actions: $str-list, box-class: $str, setup: $str}}

external-services:
    $repeat:
        $str: {$select: {$select-key: type, $select-records: {philly: $rec_philly, batch: $rec_batch, aml: $rec_aml, storage: $rec_storage, mongo: $rec_mongo, 
            vault: $rec_vault, registry: $rec_registry} } }

xt-services:
    storage: $str
    mongo: $str
    vault: $str
    target: $str

compute-targets:
    $repeat:
        $str: $rec_service

dockers:
    $repeat:
        $str: $rec_docker

setups:
    $repeat:
        $str: $rec_setup

general:
    advanced-mode: $bool
    username: $str
    azure-tenant-id: $str
    workspace: $str
    experiment: $str
    feedback: $bool
    run-cache-dir: $str
    distributed: $bool
    direct-run: $bool
    quick-start: $bool
    env-vars: $rec
    authentication: [auto, browser, device-code]
    xt-team-name: $str
    remote-control: $bool
    monitor: $str

    # TODO: move to new metrics section
    primary-metric: $str
    maximize-metric: $bool
    step-name: $str

code:
    code-dirs: $str-list
    code-upload: $bool
    code-zip: [none, fast, compress] 
    code-omit: $str-list
    xtlib-upload: $bool
    working-dir: $str

after-files:
    after-dirs: $str-list
    after-upload: $bool
    after-omit: $str-list

data:
    data-local: $str
    data-upload: $bool
    data-share-path: $str
    data-action: [none, download, mount]
    data-omit: $str-list
    data-writable: $bool

model:
    model-local: $str
    model-share-path: $str
    model-action: [none, dowhnload, mount]
    model-writable: $bool

logging:
    log: $bool
    notes: [none, before, after, all]
    mirror-files: $str
    mirror-dest: [none, storage]

internal:
    console: [none, normal, diagnostics, detail]
    stack-trace: $bool
    auto-start: $bool
    pip-freeze: $bool

commands: $str-list
  
aml-options:
    use-gpu: $bool
    framework: $str
    fw-version: $str
    user-managed: $bool
    distributed-training: [mpi, gloo, nccl]
    max-seconds: $int

early-stopping:
    early-policy: [none, bandit, median, truncation]
    delay-evaluation: $num
    evaluation-interval: $num
    slack-factor: $num
    slack-amount: $num
    truncation-percentage: $num

hyperparameter-search:
    option-prefix: $str
    aggregate-dest: [job, experiment, none]
    search-type: [random, grid, bayesian, dgd]
    max-minutes: $num
    max-runs: $int
    concurrent: $int
    hp-config: $str
    fn-generated-config: $str

hyperparameter-explorer:
    hx-cache-dir: $str
    steps-name: $str
    log-interval-name: $str
    time-name: $str
    sample-efficiency-name: $str
    success-rate-name: $str

run-reports:
    sort: $str
    group: $str
    number-groups: $bool
    reverse: $bool
    max-width: $int
    precision: $int
    uppercase-hdr: $bool
    right-align-numeric: $bool
    truncate-with-ellipses: $bool
    status: $str
    report-rollup: $bool
    columns: $str-list
    last: $int

job-reports:
    sort: $str
    reverse: $bool
    max-width: $int
    precision: $int
    uppercase-hdr: $bool
    right-align-numeric: $bool
    truncate-with-ellipses: $bool
    columns: $str-list
    last: $int

tensorboard:
    template: $str

script-launch-prefix:
    windows: $str
    linux: $str
    dsvm: $str
    azureml: $str
    philly: $str

azure-batch-images:
    $repeat:
        $str: $rec_image

boxes:
    $repeat:
        $str: $rec_box

providers:
    command: 
        $repeat: {$str: $str}

    compute: 
        $repeat: {$str: $str}

    hp-search: 
        $repeat: {$str: $str}

    storage: 
        $repeat: {$str: $str}


